---
language: objective-c

sudo: required

before_install:
  # Setup Python environment
  - source tests/terryfy/travis_tools.sh
  - export CC=clang
  - export CXX=clang++
  - get_python_environment macpython 2.7.10 venv

install:
  # Create Workspace directory
  - mkdir -p ~/Workspace/
  - cp -r ../dotfiles ~/Workspace/dotfiles

script:
  # Execute the bootstrapping script
  - cd ~/Workspace/dotfiles
  - sudo -s ./bootstrap.sh '--force --no-update'
  # Execute the update script
  - cd ~/.ansible
  - export PATH=/opt/homebrew/bin:$PATH
  - travis_wait 60 sudo -s FORCE_UNSAFE_CONFIGURE=1 ansible-playbook site.yml '-i hosts -e "brew_upgrade_all=false atom_upgrade_all=false node_upgrade_all=false"'
