---
- name: Upgrade installed Atom packages.
  command: apm upgrade
  register: return_value
  changed_when: "return_value.stdout.find('(empty)') == -1"

- name: Get list of installed Atom packages.
  shell: apm list -b -i | sed -E 's/@[0-9]+\.[0-9]+\.[0-9]+$//' | tr '[:upper:]' '[:lower:]' | sed /^$/d
  register: existing_packages
  always_run: yes
  failed_when: False
  changed_when: False

- name: Get list of configured Atom packages.
  command: cat {{ dotfiles_local }}/atom_packages
  register: packages
  always_run: yes
  changed_when: False

- name: Ensure configured Atom packages are installed.
  command: apm install {{ item }}
  with_items: packages.stdout_lines
  when: "item not in existing_packages.stdout_lines"
  changed_when: "item not in existing_packages.stdout_lines"
