---
- name: Tap the Homebrew Cask repository.
  homebrew_tap:
    tap: caskroom/cask
    state: present

- name: Install and update Homebrew Cask.
  homebrew:
    name: brew-cask
    state: present

- name: Get list of configured Homebrew Cask packages not requiring sudo.
  command: cat {{ dotfiles_local }}/cask_packages
  register: packages
  always_run: yes
  changed_when: False

- name: Ensure configured Homebrew Cask packages not requiring sudo are installed.
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: packages.stdout_lines
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ app_dir }}"

- name: Get list of configured Homebrew Cask packages requiring sudo.
  command: cat {{ dotfiles_local }}/cask_packages_sudo
  register: packages_sudo
  always_run: yes
  changed_when: False

- name: Ensure configured Homebrew Cask packages requiring sudo are installed.
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: packages_sudo.stdout_lines
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ app_dir }}"
  sudo: yes
