---
- name: Tap the Homebrew Cask repository.
  homebrew_tap:
    tap: caskroom/cask
    state: present

- name: Install and update Homebrew Cask.
  homebrew:
    name: brew-cask
    state: present

- name: Get list of configured Homebrew Cask applications not requiring sudo.
  command: cat {{ dotfiles_local }}/applications
  register: applications
  always_run: yes
  changed_when: False

- name: Ensure configured Homebrew Cask applications not requiring sudo are installed.
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: applications.stdout_lines
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ appdir }}"

- name: Get list of configured Homebrew Cask applications requiring sudo.
  command: cat {{ dotfiles_local }}/applications_sudo
  register: applications_sudo
  always_run: yes
  changed_when: False

- name: Ensure configured Homebrew Cask applications requiring sudo are installed.
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: applications_sudo.stdout_lines
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ appdir }}"
  sudo: yes
