---
- name: Assure the current user name.
  command: id -un
  register: user_name
  check_mode: no
  changed_when: False

- name: Ensure `/usr/local/bin` exists.
  file:
    path: /usr/local/bin
    owner: "{{ user_name.stdout }}"
    mode: 0755
    state: directory
  become: yes
  become_method: sudo
