---
- name: Ensure ruby is installed.
  homebrew:
    name: ["ruby", "rbenv"]
    state: present

- name: Ensure the ruby environment.
  shell: eval "$(rbenv init -)"

- name: Ensure Travis CI CLI is installed.
  gem:
    name: travis
    state: latest
    user_install: no
